dg-middleware: CorbaServerGeneric Class Reference
CorbaServerGeneric Class Reference
#include <dg-middleware/corba-server-generic.h>
Public Member Functions
CorbaServerGeneric (const std::string &contextName)
~CorbaServerGeneric (void)
void init (void)
template<class IdlReference >
void addIdl (IdlReference idl, const std::string &idlStrName)
void run (bool onlyOnce=false)
void stop (void)
void initOrb (void)
void createThreadPolicy (bool isMultiThread=true)
void createContext (const std::string &contextStrName)
void activateContext (void)
template<class IdlReference >
void activateIdl (IdlReference idl)
template<class IdlReference >
void bindIdl (IdlReference idl, const std::string &idlStrName)
template<class hppIdlReference >
void addIdl (hppIdlReference idlRef, const std::string &idlStrName)
template<class hppIdlReference >
void activateIdl (hppIdlReference idlRef)
template<class hppIdlReference >
void bindIdl (hppIdlReference idlRef, const std::string &idlStrName)
Protected Types
typedef PortableServer::ObjectId * IdlId
typedef std::list< IdlId > IdlList
Protected Attributes
CORBA::ORB_var orb
CosNaming::NamingContext_var hppContext
PortableServer::POA_var poa
IdlList idlList
std::string serverName
Member Typedef Documentation
typedef PortableServer::ObjectId* CorbaServerGeneric::IdlId [protected]
typedef std::list<IdlId> CorbaServerGeneric::IdlList [protected]
Constructor & Destructor Documentation
CorbaServerGeneric::CorbaServerGeneric (const std::string & contextName)
CorbaServerGeneric::~CorbaServerGeneric (void)
Member Function Documentation
void CorbaServerGeneric::activateContext (void)
template<class hppIdlReference > void CorbaServerGeneric::activateIdl (hppIdlReference idlRef) [inline]
References HPP_RETHROW, idlList, and poa.
template<class IdlReference > void CorbaServerGeneric::activateIdl (IdlReference idl) [inline]
Referenced by addIdl().
template<class hppIdlReference > void CorbaServerGeneric::addIdl (hppIdlReference idlRef, const std::string & idlStrName) [inline]
References activateIdl(), and bindIdl().
template<class IdlReference > void CorbaServerGeneric::addIdl (IdlReference idl, const std::string & idlStrName) [inline]
template<class hppIdlReference > void CorbaServerGeneric::bindIdl (hppIdlReference idlRef, const std::string & idlStrName) [inline]
References HPP_RETHROW, and hppContext.
template<class IdlReference > void CorbaServerGeneric::bindIdl (IdlReference idl, const std::string & idlStrName) [inline]
Referenced by addIdl().
void CorbaServerGeneric::createContext (const std::string & contextStrName)
void CorbaServerGeneric::createThreadPolicy (bool isMultiThread = true)
void CorbaServerGeneric::init (void)
void CorbaServerGeneric::initOrb (void)
void CorbaServerGeneric::run (bool onlyOnce = false)
void CorbaServerGeneric::stop (void)
Member Data Documentation
CosNaming::NamingContext_var CorbaServerGeneric::hppContext [protected]
Referenced by bindIdl().
IdlList CorbaServerGeneric::idlList [protected]
Referenced by activateIdl().
CORBA::ORB_var CorbaServerGeneric::orb [protected]
PortableServer::POA_var CorbaServerGeneric::poa [protected]
Referenced by activateIdl().
std::string CorbaServerGeneric::serverName [protected]